Use LZMA compression
The kernel is too large for the recovery partition.
This results in the error:
error: +/home/x/BUILD/cm-13.0/out/target/product/flo/recovery.img
too large (10979328 > [10813440 - 270336])
Switching from GZIP to LZMA compression shrinks the kernel
and fixes this error.

Change-Id: I12477a6430d86e7a8fff5feba82caa03114ecab8